name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v1
      
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
      
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
     
    #- name: Dependency Check Scan
    #  uses: sburris/dependency-check-action@master
    #  with:
    #    Project-Name: TestApp
    #    Report-Location: /github/workspace/dcReports
       
    #- name: Where am I?
    #  run: echo $(pwd)
       
    #- name: SHOW ME THE FILES!!!
    #  run: echo $(du -a)
               
    #- name: Upload report artifacts
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: dcReports
    #    path: /github/workspace/dcReports
