name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v1
      
    #- name: Setup .NET Core
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.0.100
      
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
    
    - name: TruffleHog Scan
      uses: sburris/truffleHog-action@master
    
    - name: Upload TruffleHog report
      uses: actions/upload-artifact@v1
      with:
        name: truffleHog-Report
        # This directory path is pointing to the same logical directory above but 
        # outside the docker container
        path: ${{ github.workspace }}/reports

    - name: Lets check files
      run: ll ${{ github.workspace }}

    ## FAIL - didn't put anything out to the screen and looks like no files are outputted.
    ##   Tried updated regex put didn't work
    #- name: Trufflehog Actions Scan
    #  uses: edplato/trufflehog-actions-scan@custom-rules   

    # UNKNOWN - have not tried
    # Looking at code, it seems to take the TruffleHog regex patterns for tokens and runs them.
    # Can output to slack which is nice, but don't have slack setup for testing
    # Slack is not required, not sure what sort of output is produced.
    #- name: GitSecure-BugBountySite
    #  uses: bugbounty-site/GitSecure@v1    

    # FAIL
    #- name: gitleaks-action
    #  uses: eshork/gitleaks-action@master

    # FAIL
    #  # Is truffleHog under the covers
    #  #  Ran, didn't fail, but didn't print anything out
    #  #  When ran locally did find a ton of stuff
    #  #  Wonder what I did wrong or if I am not looking in the right location
    #- name: Secret Scan
    #  uses: max/secret-scan@1.0.0


    # SUCCESS
    #- name: Snyk Scan
    #  uses: snyk/actions/dotnet@master
    #  env:
    #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # SUCCESS
    #- name: Dependency Check Scan
    #  uses: sburris/dependency-check-action@v0.1-beta
    #  with:
    #    Project-Name: TestApp
    #    # The directory path specified here is specific to inside the docker container
    #    Report-Location: /github/workspace/dcReports
    #    Report-Format: HTML
    #    Log-Name: MyLog.txt
             
    # SUCCESS (to be used with above action)
    #- name: Upload report artifacts
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: dcReports
    #    # This directory path is pointing to the same logical directory above but 
    #    # outside the docker container
    #    path: ${{ github.workspace }}/dcReports
